//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberCourse
    {
        public string MemberCourseNo { get; set; }
        public string Member_No { get; set; }
        public string CourseSeries_No { get; set; }
        public bool PayStatus { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int NumberOfCourse { get; set; }
    
        public virtual CourseSeries CourseSeries { get; set; }
        public virtual Member Member { get; set; }
    }
}
