// <auto-generated />
namespace Gym.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AlterCourseItem_TeacherNo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterCourseItem_TeacherNo));
        
        string IMigrationMetadata.Id
        {
            get { return "201908301118010_AlterCourseItem_TeacherNo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
